baseURL = "https://eason.blog/"
languageCode = "en-us"
title = "Lee Eason's personal blog"
theme = "aether"
googleAnalytics = "G-2N3C69L9GL"

[params]
  brand = "Eason Development"
  description = "Pragmatic software development tips from the front lines"
  homeimg = "/images/footer-hex.png"
  twitterHandle = "leejeason"
  shareOnLinkedIn = true
  shareOnTwitter = true
